'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useParams, useSearchParams } from 'next/navigation';
import { Card } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { StatusBadge } from '@/components/ui/status-badge';
import { Button } from '@/components/ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Calendar } from '@/components/ui/calendar';
import { Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowRight, ArrowUpRight, ArrowDownRight, Calendar as CalendarIcon, Globe, Twitter, ExternalLink } from 'lucide-react';
import { formatDate } from '@/lib/dateFormat';

/**
 * /public/mindshare/[token] — client-facing before/after mindshare report.
 *
 * Landing URL uses a share token (generated by Andy from the /mindshare
 * Projects tab). Defaults to "last 30 days vs the 30 days before that",
 * but the client can drop the "campaign start" pivot in to see the exact
 * story: baseline before HHP kicked in vs. what happened after.
 *
 * Kept intentionally read-only — a shareable snapshot, not an editable
 * dashboard. Sample of channels is exposed for transparency ("here's
 * where we're measuring, not a black box").
 */

type WindowStat = {
  from: string;
  to: string;
  days: number;
  mentions: number;
  total_market_mentions: number;
  mindshare_pct: number;
  channels_reached: number;
};

type MindshareData = {
  project: {
    id: string;
    name: string;
    category: string | null;
    is_pre_tge: boolean;
    twitter_handle: string | null;
    website_url: string | null;
    description: string | null;
    client_name: string | null;
  };
  window_days: number;
  before: WindowStat;
  after: WindowStat;
  delta: {
    mindshare_pct_points: number;
    mentions_change_pct: number;
  };
  series: Array<{ day: string; mentions: number; channels: number; total: number; mindshare_pct: number }>;
  top_channels: Array<{ name: string; username: string | null; member_count: number | null; count: number }>;
  generated_at: string;
};

// Compact chart tick ("Jun 5") — full mm/dd/yyyy overflows the daily
// mindshare X axis (CLAUDE.md chart-axis carve-out).
// lint-conventions: disable-next-line no-raw-toLocaleDateString
const formatChartTick = (d: string) => new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });

export default function PublicMindsharePage() {
  const params = useParams<{ token: string }>();
  const searchParams = useSearchParams();
  const initialPivot = searchParams.get('after') || '';
  const initialWindow = Number(searchParams.get('window') || '30');

  const [data, setData] = useState<MindshareData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [pivot, setPivot] = useState<string>(initialPivot);
  const [windowDays, setWindowDays] = useState<number>(initialWindow);
  const [datePickerOpen, setDatePickerOpen] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const url = new URL(`/api/public/mindshare/${params.token}`, window.location.origin);
      if (pivot) url.searchParams.set('after', pivot);
      url.searchParams.set('window', String(windowDays));
      const res = await fetch(url.toString());
      const json = await res.json();
      if (!res.ok) throw new Error(json?.error || `HTTP ${res.status}`);
      setData(json);
    } catch (err: any) {
      setError(err?.message || 'Failed to load');
    } finally {
      setLoading(false);
    }
  }, [params.token, pivot, windowDays]);

  useEffect(() => { load(); }, [load]);

  const deltaTone = useMemo(() => {
    if (!data) return 'neutral' as const;
    const d = data.delta.mindshare_pct_points;
    if (d > 0.05) return 'success' as const;
    if (d < -0.05) return 'danger' as const;
    return 'neutral' as const;
  }, [data]);

  const chartData = useMemo(() => {
    if (!data) return [];
    return data.series.map(s => ({
      day: s.day,
      pct: Number(s.mindshare_pct.toFixed(3)),
      mentions: s.mentions,
    }));
  }, [data]);

  if (loading) {
    return (
      <div className="max-w-5xl mx-auto p-6 space-y-6">
        <Skeleton className="h-24 rounded-xl" />
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {Array.from({ length: 3 }).map((_, i) => <Skeleton key={i} className="h-28 rounded-xl" />)}
        </div>
        <Skeleton className="h-72 rounded-lg" />
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="max-w-3xl mx-auto p-12 text-center">
        <div className="inline-flex items-center justify-center h-14 w-14 rounded-full bg-rose-50 text-rose-600 mb-4">
          <ExternalLink className="h-6 w-6" />
        </div>
        <h1 className="text-2xl font-bold text-gray-900 mb-2">Report unavailable</h1>
        <p className="text-sm text-gray-600">{error ?? "This link may have expired or been rotated. Reach out to your HoloHive contact for a fresh one."}</p>
      </div>
    );
  }

  const { project, before, after, delta } = data;

  return (
    <div className="max-w-5xl mx-auto p-6 space-y-6">
      {/* Hero — project + range picker */}
      <Card className="overflow-hidden border-gray-200">
        <div className="bg-gradient-to-br from-brand/10 to-brand/5 p-6 border-b border-gray-100">
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="text-[10px] uppercase tracking-[0.14em] text-brand font-semibold mb-1">Mindshare Report</div>
              <h1 className="text-3xl font-bold text-gray-900 flex items-center gap-3">
                {project.name}
                {project.is_pre_tge && <StatusBadge tone="purple" size="sm">Pre-TGE</StatusBadge>}
              </h1>
              {project.description && (
                <p className="text-sm text-gray-600 mt-2 max-w-2xl">{project.description}</p>
              )}
              <div className="flex items-center gap-3 mt-3 text-xs text-gray-500">
                {project.category && <span>{project.category}</span>}
                {project.twitter_handle && (
                  <a href={`https://twitter.com/${project.twitter_handle.replace('@','')}`} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 hover:text-brand">
                    <Twitter className="h-3 w-3" />@{project.twitter_handle.replace('@','')}
                  </a>
                )}
                {project.website_url && (
                  <a href={project.website_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 hover:text-brand">
                    <Globe className="h-3 w-3" />Website
                  </a>
                )}
              </div>
            </div>
            <div className="flex flex-col items-end gap-2">
              <div className="text-[10px] uppercase tracking-[0.14em] text-gray-500 font-semibold">Window</div>
              <Popover open={datePickerOpen} onOpenChange={setDatePickerOpen}>
                <PopoverTrigger asChild>
                  <Button variant="outline" size="sm" className="h-9 focus-brand gap-1.5">
                    <CalendarIcon className="h-3.5 w-3.5" />
                    {pivot ? `Campaign start: ${formatDate(pivot)}` : `Last ${windowDays} days`}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="!bg-white border shadow-md p-3 w-auto z-[80]" align="end">
                  <div className="mb-2 text-[11px] text-gray-500">Pick the campaign start date — before/after windows anchor around it.</div>
                  <Calendar
                    mode="single"
                    selected={pivot ? new Date(pivot + 'T00:00:00Z') : undefined}
                    onSelect={(d) => {
                      if (d) {
                        setPivot(d.toISOString().slice(0, 10));
                        setDatePickerOpen(false);
                      }
                    }}
                    classNames={{ day_selected: 'text-white hover:text-white focus:text-white' }}
                    modifiersStyles={{ selected: { backgroundColor: '#3e8692' } }}
                  />
                  <div className="mt-2 flex gap-1">
                    {[14, 30, 60, 90].map(n => (
                      <Button
                        key={n}
                        type="button"
                        variant={windowDays === n ? 'brand' : 'outline'}
                        size="sm"
                        className="h-7 text-[11px] flex-1"
                        onClick={() => setWindowDays(n)}
                      >
                        ±{n}d
                      </Button>
                    ))}
                  </div>
                  {pivot && (
                    <Button variant="ghost" size="sm" className="w-full h-7 mt-2 text-[11px] text-gray-500" onClick={() => { setPivot(''); setDatePickerOpen(false); }}>
                      Clear pivot
                    </Button>
                  )}
                </PopoverContent>
              </Popover>
            </div>
          </div>
        </div>

        {/* Before → After hero row */}
        <div className="grid grid-cols-1 md:grid-cols-[1fr_auto_1fr] gap-4 p-6 items-center">
          <WindowCard label="Before" stat={before} accent="neutral" />
          <div className="flex flex-col items-center gap-2">
            <ArrowRight className="h-6 w-6 text-brand" />
            <StatusBadge tone={deltaTone} size="sm">
              {delta.mindshare_pct_points >= 0 ? '+' : ''}{delta.mindshare_pct_points.toFixed(2)}pp
            </StatusBadge>
            <div className="text-[10px] uppercase tracking-[0.14em] text-gray-500 text-center">
              {delta.mentions_change_pct >= 0 ? '+' : ''}{delta.mentions_change_pct.toFixed(0)}% mentions
            </div>
          </div>
          <WindowCard label="After" stat={after} accent="brand" />
        </div>
      </Card>

      {/* Trajectory chart */}
      <Card className="border-gray-200 p-4">
        <div className="text-[10px] uppercase tracking-[0.14em] text-gray-500 font-semibold mb-2">Daily mindshare</div>
        <div className="h-56">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={chartData} margin={{ top: 8, right: 12, bottom: 4, left: -12 }}>
              <XAxis
                dataKey="day"
                tickFormatter={formatChartTick}
                tick={{ fontSize: 10, fill: '#6b7280' }}
                axisLine={{ stroke: '#e5e7eb' }}
                tickLine={false}
              />
              <YAxis
                tickFormatter={(v) => `${Number(v).toFixed(1)}%`}
                tick={{ fontSize: 10, fill: '#6b7280' }}
                axisLine={{ stroke: '#e5e7eb' }}
                tickLine={false}
                width={44}
              />
              <Tooltip
                labelFormatter={(d) => formatDate(String(d))}
                formatter={(v: any, name: string) => name === 'pct' ? [`${Number(v).toFixed(2)}%`, 'Mindshare'] : [v, 'Mentions']}
                contentStyle={{ background: 'white', border: '1px solid #e5e7eb', borderRadius: 6, fontSize: 12 }}
              />
              <ReferenceLine x={after.from} stroke="#3e8692" strokeDasharray="3 3" label={{ value: 'Campaign start', position: 'top', fill: '#3e8692', fontSize: 10 }} />
              <Line type="monotone" dataKey="pct" stroke="#3e8692" strokeWidth={2} dot={false} />
            </LineChart>
          </ResponsiveContainer>
        </div>
        <div className="text-[10px] text-gray-500 mt-2">
          % of tracked Korean Telegram mentions attributed to {project.name} on each day.
        </div>
      </Card>

      {/* Top channels — the transparency layer. Clients need to trust the sample. */}
      <Card className="border-gray-200 p-4">
        <div className="flex items-center justify-between mb-3">
          <div>
            <div className="text-[10px] uppercase tracking-[0.14em] text-gray-500 font-semibold">Top channels driving mentions</div>
            <div className="text-xs text-gray-500 mt-0.5">In the after-window ({formatDate(after.from)} – {formatDate(after.to)})</div>
          </div>
          <StatusBadge tone="neutral" size="sm">{after.channels_reached} channels</StatusBadge>
        </div>
        {data.top_channels.length === 0 ? (
          <div className="text-xs text-gray-500 py-4 text-center">No channel-level attribution for this window yet.</div>
        ) : (
          <ul className="divide-y divide-gray-100">
            {data.top_channels.map((c, i) => (
              <li key={c.name + i} className="py-2 flex items-center justify-between gap-3">
                <div className="min-w-0">
                  <div className="text-sm text-gray-900 truncate">
                    {c.username ? (
                      <a href={`https://t.me/${c.username}`} target="_blank" rel="noopener noreferrer" className="hover:text-brand inline-flex items-center gap-1">
                        {c.name}
                        <ExternalLink className="h-3 w-3 opacity-50" />
                      </a>
                    ) : (
                      c.name
                    )}
                  </div>
                  {c.member_count != null && (
                    <div className="text-[11px] text-gray-500 tabular-nums">{c.member_count.toLocaleString('en-US')} members</div>
                  )}
                </div>
                <div className="text-sm font-medium text-gray-700 tabular-nums">{c.count} mentions</div>
              </li>
            ))}
          </ul>
        )}
      </Card>

      {/* Footer — provenance + generated stamp so nothing looks black-box */}
      <div className="text-[10px] text-gray-400 text-center pt-4 space-y-1">
        <div>Report generated {formatDate(data.generated_at)}. Window: {data.window_days} days.</div>
        <div>Mindshare = tracked mentions divided by all mentions across the same Telegram channel set for the same day.</div>
      </div>
    </div>
  );
}

function WindowCard({ label, stat, accent }: { label: string; stat: WindowStat; accent: 'brand' | 'neutral' }) {
  const isBrand = accent === 'brand';
  return (
    <div className={`rounded-lg p-4 ${isBrand ? 'bg-brand text-white' : 'bg-gray-50 border border-gray-100'}`}>
      <div className={`text-[10px] uppercase tracking-[0.14em] font-semibold ${isBrand ? 'text-white/80' : 'text-gray-500'}`}>{label}</div>
      <div className="mt-1 flex items-baseline gap-1">
        <div className={`text-3xl font-bold tabular-nums ${isBrand ? 'text-white' : 'text-gray-900'}`}>{stat.mindshare_pct.toFixed(2)}</div>
        <div className={`text-sm font-semibold ${isBrand ? 'text-white/80' : 'text-gray-500'}`}>%</div>
      </div>
      <div className={`text-[11px] mt-2 ${isBrand ? 'text-white/70' : 'text-gray-500'}`}>
        {formatDate(stat.from)} → {formatDate(stat.to)}
      </div>
      <div className={`text-[11px] tabular-nums ${isBrand ? 'text-white/70' : 'text-gray-500'}`}>
        {stat.mentions.toLocaleString('en-US')} mentions of {stat.total_market_mentions.toLocaleString('en-US')} tracked
      </div>
    </div>
  );
}
